using System.Numerics;

namespace Rin.Shade;

// [SlangExpression]-bound math builtins, one overload per width (generics aren't supported, SHADE0008).
// Generated by scripts/gen_math_intrinsics.py - do not hand-edit, regenerate instead.
public abstract partial class Shader
{
    public static class Math
    {
        [SlangExpression("abs(@0)")]
        public static extern float Abs(float x);
        [SlangExpression("abs(@0)")]
        public static extern Vector2 Abs(Vector2 x);
        [SlangExpression("abs(@0)")]
        public static extern Vector3 Abs(Vector3 x);
        [SlangExpression("abs(@0)")]
        public static extern Vector4 Abs(Vector4 x);

        [SlangExpression("sign(@0)")]
        public static extern float Sign(float x);
        [SlangExpression("sign(@0)")]
        public static extern Vector2 Sign(Vector2 x);
        [SlangExpression("sign(@0)")]
        public static extern Vector3 Sign(Vector3 x);
        [SlangExpression("sign(@0)")]
        public static extern Vector4 Sign(Vector4 x);

        [SlangExpression("floor(@0)")]
        public static extern float Floor(float x);
        [SlangExpression("floor(@0)")]
        public static extern Vector2 Floor(Vector2 x);
        [SlangExpression("floor(@0)")]
        public static extern Vector3 Floor(Vector3 x);
        [SlangExpression("floor(@0)")]
        public static extern Vector4 Floor(Vector4 x);

        [SlangExpression("ceil(@0)")]
        public static extern float Ceil(float x);
        [SlangExpression("ceil(@0)")]
        public static extern Vector2 Ceil(Vector2 x);
        [SlangExpression("ceil(@0)")]
        public static extern Vector3 Ceil(Vector3 x);
        [SlangExpression("ceil(@0)")]
        public static extern Vector4 Ceil(Vector4 x);

        [SlangExpression("round(@0)")]
        public static extern float Round(float x);
        [SlangExpression("round(@0)")]
        public static extern Vector2 Round(Vector2 x);
        [SlangExpression("round(@0)")]
        public static extern Vector3 Round(Vector3 x);
        [SlangExpression("round(@0)")]
        public static extern Vector4 Round(Vector4 x);

        [SlangExpression("frac(@0)")]
        public static extern float Frac(float x);
        [SlangExpression("frac(@0)")]
        public static extern Vector2 Frac(Vector2 x);
        [SlangExpression("frac(@0)")]
        public static extern Vector3 Frac(Vector3 x);
        [SlangExpression("frac(@0)")]
        public static extern Vector4 Frac(Vector4 x);

        [SlangExpression("sqrt(@0)")]
        public static extern float Sqrt(float x);
        [SlangExpression("sqrt(@0)")]
        public static extern Vector2 Sqrt(Vector2 x);
        [SlangExpression("sqrt(@0)")]
        public static extern Vector3 Sqrt(Vector3 x);
        [SlangExpression("sqrt(@0)")]
        public static extern Vector4 Sqrt(Vector4 x);

        [SlangExpression("rsqrt(@0)")]
        public static extern float Rsqrt(float x);
        [SlangExpression("rsqrt(@0)")]
        public static extern Vector2 Rsqrt(Vector2 x);
        [SlangExpression("rsqrt(@0)")]
        public static extern Vector3 Rsqrt(Vector3 x);
        [SlangExpression("rsqrt(@0)")]
        public static extern Vector4 Rsqrt(Vector4 x);

        [SlangExpression("saturate(@0)")]
        public static extern float Saturate(float x);
        [SlangExpression("saturate(@0)")]
        public static extern Vector2 Saturate(Vector2 x);
        [SlangExpression("saturate(@0)")]
        public static extern Vector3 Saturate(Vector3 x);
        [SlangExpression("saturate(@0)")]
        public static extern Vector4 Saturate(Vector4 x);

        [SlangExpression("exp(@0)")]
        public static extern float Exp(float x);
        [SlangExpression("exp(@0)")]
        public static extern Vector2 Exp(Vector2 x);
        [SlangExpression("exp(@0)")]
        public static extern Vector3 Exp(Vector3 x);
        [SlangExpression("exp(@0)")]
        public static extern Vector4 Exp(Vector4 x);

        [SlangExpression("exp2(@0)")]
        public static extern float Exp2(float x);
        [SlangExpression("exp2(@0)")]
        public static extern Vector2 Exp2(Vector2 x);
        [SlangExpression("exp2(@0)")]
        public static extern Vector3 Exp2(Vector3 x);
        [SlangExpression("exp2(@0)")]
        public static extern Vector4 Exp2(Vector4 x);

        [SlangExpression("log(@0)")]
        public static extern float Log(float x);
        [SlangExpression("log(@0)")]
        public static extern Vector2 Log(Vector2 x);
        [SlangExpression("log(@0)")]
        public static extern Vector3 Log(Vector3 x);
        [SlangExpression("log(@0)")]
        public static extern Vector4 Log(Vector4 x);

        [SlangExpression("log2(@0)")]
        public static extern float Log2(float x);
        [SlangExpression("log2(@0)")]
        public static extern Vector2 Log2(Vector2 x);
        [SlangExpression("log2(@0)")]
        public static extern Vector3 Log2(Vector3 x);
        [SlangExpression("log2(@0)")]
        public static extern Vector4 Log2(Vector4 x);

        [SlangExpression("sin(@0)")]
        public static extern float Sin(float x);
        [SlangExpression("sin(@0)")]
        public static extern Vector2 Sin(Vector2 x);
        [SlangExpression("sin(@0)")]
        public static extern Vector3 Sin(Vector3 x);
        [SlangExpression("sin(@0)")]
        public static extern Vector4 Sin(Vector4 x);

        [SlangExpression("cos(@0)")]
        public static extern float Cos(float x);
        [SlangExpression("cos(@0)")]
        public static extern Vector2 Cos(Vector2 x);
        [SlangExpression("cos(@0)")]
        public static extern Vector3 Cos(Vector3 x);
        [SlangExpression("cos(@0)")]
        public static extern Vector4 Cos(Vector4 x);

        [SlangExpression("tan(@0)")]
        public static extern float Tan(float x);
        [SlangExpression("tan(@0)")]
        public static extern Vector2 Tan(Vector2 x);
        [SlangExpression("tan(@0)")]
        public static extern Vector3 Tan(Vector3 x);
        [SlangExpression("tan(@0)")]
        public static extern Vector4 Tan(Vector4 x);

        [SlangExpression("asin(@0)")]
        public static extern float Asin(float x);
        [SlangExpression("asin(@0)")]
        public static extern Vector2 Asin(Vector2 x);
        [SlangExpression("asin(@0)")]
        public static extern Vector3 Asin(Vector3 x);
        [SlangExpression("asin(@0)")]
        public static extern Vector4 Asin(Vector4 x);

        [SlangExpression("acos(@0)")]
        public static extern float Acos(float x);
        [SlangExpression("acos(@0)")]
        public static extern Vector2 Acos(Vector2 x);
        [SlangExpression("acos(@0)")]
        public static extern Vector3 Acos(Vector3 x);
        [SlangExpression("acos(@0)")]
        public static extern Vector4 Acos(Vector4 x);

        [SlangExpression("atan(@0)")]
        public static extern float Atan(float x);
        [SlangExpression("atan(@0)")]
        public static extern Vector2 Atan(Vector2 x);
        [SlangExpression("atan(@0)")]
        public static extern Vector3 Atan(Vector3 x);
        [SlangExpression("atan(@0)")]
        public static extern Vector4 Atan(Vector4 x);

        [SlangExpression("radians(@0)")]
        public static extern float Radians(float x);
        [SlangExpression("radians(@0)")]
        public static extern Vector2 Radians(Vector2 x);
        [SlangExpression("radians(@0)")]
        public static extern Vector3 Radians(Vector3 x);
        [SlangExpression("radians(@0)")]
        public static extern Vector4 Radians(Vector4 x);

        [SlangExpression("degrees(@0)")]
        public static extern float Degrees(float x);
        [SlangExpression("degrees(@0)")]
        public static extern Vector2 Degrees(Vector2 x);
        [SlangExpression("degrees(@0)")]
        public static extern Vector3 Degrees(Vector3 x);
        [SlangExpression("degrees(@0)")]
        public static extern Vector4 Degrees(Vector4 x);

        [SlangExpression("min(@0, @1)")]
        public static extern float Min(float a, float b);
        [SlangExpression("min(@0, @1)")]
        public static extern Vector2 Min(Vector2 a, Vector2 b);
        [SlangExpression("min(@0, @1)")]
        public static extern Vector3 Min(Vector3 a, Vector3 b);
        [SlangExpression("min(@0, @1)")]
        public static extern Vector4 Min(Vector4 a, Vector4 b);

        [SlangExpression("max(@0, @1)")]
        public static extern float Max(float a, float b);
        [SlangExpression("max(@0, @1)")]
        public static extern Vector2 Max(Vector2 a, Vector2 b);
        [SlangExpression("max(@0, @1)")]
        public static extern Vector3 Max(Vector3 a, Vector3 b);
        [SlangExpression("max(@0, @1)")]
        public static extern Vector4 Max(Vector4 a, Vector4 b);

        [SlangExpression("pow(@0, @1)")]
        public static extern float Pow(float a, float b);
        [SlangExpression("pow(@0, @1)")]
        public static extern Vector2 Pow(Vector2 a, Vector2 b);
        [SlangExpression("pow(@0, @1)")]
        public static extern Vector3 Pow(Vector3 a, Vector3 b);
        [SlangExpression("pow(@0, @1)")]
        public static extern Vector4 Pow(Vector4 a, Vector4 b);

        [SlangExpression("step(@0, @1)")]
        public static extern float Step(float a, float b);
        [SlangExpression("step(@0, @1)")]
        public static extern Vector2 Step(Vector2 a, Vector2 b);
        [SlangExpression("step(@0, @1)")]
        public static extern Vector3 Step(Vector3 a, Vector3 b);
        [SlangExpression("step(@0, @1)")]
        public static extern Vector4 Step(Vector4 a, Vector4 b);

        [SlangExpression("atan2(@0, @1)")]
        public static extern float Atan2(float a, float b);
        [SlangExpression("atan2(@0, @1)")]
        public static extern Vector2 Atan2(Vector2 a, Vector2 b);
        [SlangExpression("atan2(@0, @1)")]
        public static extern Vector3 Atan2(Vector3 a, Vector3 b);
        [SlangExpression("atan2(@0, @1)")]
        public static extern Vector4 Atan2(Vector4 a, Vector4 b);

        [SlangExpression("clamp(@0, @1, @2)")]
        public static extern float Clamp(float x, float lo, float hi);
        [SlangExpression("clamp(@0, @1, @2)")]
        public static extern Vector2 Clamp(Vector2 x, Vector2 lo, Vector2 hi);
        [SlangExpression("clamp(@0, @1, @2)")]
        public static extern Vector3 Clamp(Vector3 x, Vector3 lo, Vector3 hi);
        [SlangExpression("clamp(@0, @1, @2)")]
        public static extern Vector4 Clamp(Vector4 x, Vector4 lo, Vector4 hi);

        [SlangExpression("smoothstep(@0, @1, @2)")]
        public static extern float SmoothStep(float edge0, float edge1, float x);
        [SlangExpression("smoothstep(@0, @1, @2)")]
        public static extern Vector2 SmoothStep(Vector2 edge0, Vector2 edge1, Vector2 x);
        [SlangExpression("smoothstep(@0, @1, @2)")]
        public static extern Vector3 SmoothStep(Vector3 edge0, Vector3 edge1, Vector3 x);
        [SlangExpression("smoothstep(@0, @1, @2)")]
        public static extern Vector4 SmoothStep(Vector4 edge0, Vector4 edge1, Vector4 x);

        [SlangExpression("lerp(@0, @1, @2)")]
        public static extern float Lerp(float a, float b, float t);
        [SlangExpression("lerp(@0, @1, @2)")]
        public static extern Vector2 Lerp(Vector2 a, Vector2 b, float t);
        [SlangExpression("lerp(@0, @1, @2)")]
        public static extern Vector3 Lerp(Vector3 a, Vector3 b, float t);
        [SlangExpression("lerp(@0, @1, @2)")]
        public static extern Vector4 Lerp(Vector4 a, Vector4 b, float t);

        [SlangExpression("normalize(@0)")]
        public static extern Vector2 Normalize(Vector2 v);
        [SlangExpression("normalize(@0)")]
        public static extern Vector3 Normalize(Vector3 v);
        [SlangExpression("normalize(@0)")]
        public static extern Vector4 Normalize(Vector4 v);

        [SlangExpression("length(@0)")]
        public static extern float Length(Vector2 v);
        [SlangExpression("length(@0)")]
        public static extern float Length(Vector3 v);
        [SlangExpression("length(@0)")]
        public static extern float Length(Vector4 v);

        [SlangExpression("dot(@0, @1)")]
        public static extern float Dot(Vector2 a, Vector2 b);
        [SlangExpression("dot(@0, @1)")]
        public static extern float Dot(Vector3 a, Vector3 b);
        [SlangExpression("dot(@0, @1)")]
        public static extern float Dot(Vector4 a, Vector4 b);

        [SlangExpression("distance(@0, @1)")]
        public static extern float Distance(Vector2 a, Vector2 b);
        [SlangExpression("distance(@0, @1)")]
        public static extern float Distance(Vector3 a, Vector3 b);
        [SlangExpression("distance(@0, @1)")]
        public static extern float Distance(Vector4 a, Vector4 b);

        [SlangExpression("reflect(@0, @1)")]
        public static extern Vector2 Reflect(Vector2 i, Vector2 n);
        [SlangExpression("reflect(@0, @1)")]
        public static extern Vector3 Reflect(Vector3 i, Vector3 n);
        [SlangExpression("reflect(@0, @1)")]
        public static extern Vector4 Reflect(Vector4 i, Vector4 n);

        [SlangExpression("refract(@0, @1, @2)")]
        public static extern Vector2 Refract(Vector2 i, Vector2 n, float eta);
        [SlangExpression("refract(@0, @1, @2)")]
        public static extern Vector3 Refract(Vector3 i, Vector3 n, float eta);
        [SlangExpression("refract(@0, @1, @2)")]
        public static extern Vector4 Refract(Vector4 i, Vector4 n, float eta);

        [SlangExpression("cross(@0, @1)")]
        public static extern Vector3 Cross(Vector3 a, Vector3 b);
    }
}
