<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="$(EngineDir)Rin.Core\Rin.Core.csproj" />
    </ItemGroup>

    <ItemGroup Label="Content">
        <EmbeddedResource Include="Content\**\*.*"/>
    </ItemGroup>

</Project>
