<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="$(EngineDir)Rin.World\Rin.World.csproj" />
        <ProjectReference Include="..\Common\Examples.Common.csproj"/>
    </ItemGroup>

    <ItemGroup Label="Content">
        <EmbeddedResource Include="Content\**\*.*" Exclude="Content\**\*.slang"/>
    </ItemGroup>

    <ItemGroup Label="Slang shaders">
        <RinSlangSource Include="Content\mesh.slang" />
    </ItemGroup>
    <PropertyGroup Label="Slang shaders">
        <RinSlangOutputSubpath>Content\</RinSlangOutputSubpath>
    </PropertyGroup>
    <Import Project="$(RinMSBuildDir)RinSlang.targets" />

    <ItemGroup>
        <PackageReference Include="SharpGLTF.Core"/>
        <PackageReference Include="JetBrains.Annotations" PrivateAssets="All"/>
    </ItemGroup>

</Project>
