<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Engine\Rin.World\Rin.World.csproj" />
        <ProjectReference Include="..\Common\Examples.Common.csproj"/>
    </ItemGroup>

    <ItemGroup Label="Content">
        <EmbeddedResource Include="Content\**\*.*" Exclude="Content\**\*.slang"/>
    </ItemGroup>

    <ItemGroup Label="Slang shaders">
        <RinSlangSource Include="Content\mesh.slang" />
    </ItemGroup>
    <PropertyGroup Label="Slang shaders">
        <RinSlangOutputSubpath>Content\</RinSlangOutputSubpath>
    </PropertyGroup>
    <Import Project="..\..\msbuild\RinSlang.targets" />

    <ItemGroup>
        <PackageReference Include="SharpGLTF.Core" Version="1.0.4"/>
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" PrivateAssets="All"/>
    </ItemGroup>

</Project>
