<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="$(EngineDir)Rin.World\Rin.World.csproj" />
        <ProjectReference Include="..\Common\Examples.Common.csproj"/>
    </ItemGroup>

    <ItemGroup Label="Content">
        <EmbeddedResource Include="Content\**\*.*" Exclude="Content\**\*.slang"/>
    </ItemGroup>

    <ItemGroup Label="Rin.Shade">
        <ProjectReference Include="$(ShadeDir)Rin.Shade\Rin.Shade.csproj" />
        <ProjectReference Include="$(ShadeDir)Rin.Shade.SourceGenerator\Rin.Shade.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>
    <PropertyGroup Label="Rin.Shade">
        <RinShadeDiscoverPrefix>Shaders/Sponza/</RinShadeDiscoverPrefix>
        <RinShadeOutputSubpath>Content\Shaders\Sponza\</RinShadeOutputSubpath>
    </PropertyGroup>
    <Import Project="$(RinMSBuildDir)RinShade.targets" />

    <ItemGroup>
        <PackageReference Include="SharpGLTF.Core"/>
        <PackageReference Include="JetBrains.Annotations" PrivateAssets="All"/>
    </ItemGroup>

</Project>
