<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="$(EngineDir)Rin.World\Rin.World.csproj" />
        <ProjectReference Include="$(EngineDir)Rin.Core\Rin.Core.csproj" />
        <ProjectReference Include="$(EngineDir)Rin.GLTF\Rin.GLTF.csproj" />
        <ProjectReference Include="..\Common\Examples.Common.csproj"/>
    </ItemGroup>

    <ItemGroup Label="Reuse SceneTest's model assets rather than duplicating them">
        <Content Include="$(ExamplesDir)SceneTest\assets\models\fox.glb">
            <Link>assets\models\fox.glb</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
