<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Common\Examples.Common.csproj"/>
        <ProjectReference Include="..\RenderGraphOverlay\RenderGraphOverlay.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" PrivateAssets="All"/>
    </ItemGroup>

</Project>
