using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Rin.Shade.SourceGenerator;

/// <summary>
/// Finds every [ShadeExport]-marked class/struct and generates one const string per containing
/// file, holding that file's exact source text - the raw material ScratchCompilationBuilder (in
/// Rin.Shade.Transpiler) re-parses downstream. Nothing is interpreted or transformed here, just
/// copied verbatim, so there's no version-coupling between this generator's output and whatever
/// BodyLowering/etc. can handle later - unlike embedding a resolved AST, that interpretation only
/// ever happens at the consumer's own build, with whatever transpiler is current then.
/// </summary>
[Generator]
public class ShadeExportSourceGenerator : IIncrementalGenerator
{
    private const string ShadeExportAttributeFullName = "Rin.Shade.ShadeExportAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var exportedTrees = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 }
                    or StructDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => GetTreeIfExported(ctx))
            .Where(static tree => tree is not null)
            .Collect();

        context.RegisterSourceOutput(exportedTrees, static (spc, trees) => Execute(spc, trees));
    }

    private static SyntaxTree? GetTreeIfExported(GeneratorSyntaxContext context)
    {
        var declaration = (MemberDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(declaration);
        if (symbol is null) return null;

        var isExported = symbol.GetAttributes()
            .Any(a => a.AttributeClass?.ToDisplayString() == ShadeExportAttributeFullName);

        return isExported ? declaration.SyntaxTree : null;
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<SyntaxTree?> trees)
    {
        var uniqueTrees = trees.Where(t => t is not null).Distinct().ToArray();
        if (uniqueTrees.Length == 0) return;

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("[assembly: Rin.Shade.ShaderSources]");
        builder.AppendLine();
        builder.AppendLine("namespace Rin.Shade.Generated;");
        builder.AppendLine();
        builder.AppendLine("internal static class ShaderSourceContainer");
        builder.AppendLine("{");

        var usedNames = new HashSet<string>();
        foreach (var tree in uniqueTrees)
        {
            var fieldName = MakeSafeFieldName(tree!.FilePath, usedNames);
            var literal = SymbolDisplay.FormatLiteral(tree.GetText().ToString(), quote: true);
            builder.AppendLine($"    public const string {fieldName} = {literal};");
        }

        builder.AppendLine("}");

        context.AddSource("ShaderSourceContainer.g.cs", builder.ToString());
    }

    private static string MakeSafeFieldName(string filePath, HashSet<string> usedNames)
    {
        var name = Path.GetFileNameWithoutExtension(filePath);
        var safe = new StringBuilder();
        foreach (var c in name)
            safe.Append(char.IsLetterOrDigit(c) ? c : '_');

        if (safe.Length == 0 || char.IsDigit(safe[0])) safe.Insert(0, '_');

        var candidate = safe.ToString();
        var suffix = 1;
        while (!usedNames.Add(candidate))
            candidate = $"{safe}_{suffix++}";

        return candidate;
    }
}
