using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Rin.Shade.SourceGenerator;

/// <summary>
/// Emits a <c>public const string Path</c> on every <c>[Shader("...")]</c> class, holding the
/// attribute's path argument so consumers can reference it instead of retyping the literal. It is a
/// const because attribute arguments need compile-time constants. The class must be partial.
/// </summary>
[Generator]
public class ShaderPathSourceGenerator : IIncrementalGenerator
{
    private const string ShaderAttributeFullName = "Rin.Shade.ShaderAttribute";

    private static readonly DiagnosticDescriptor MissingPartial = new(
        id: "SHADEGEN0001",
        title: "[Shader] class must be partial",
        messageFormat: "'{0}' is marked [Shader(...)] but isn't declared 'partial' - the generated Path constant can't be added without it",
        category: "Rin.Shade",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor NestedShaderClass = new(
        id: "SHADEGEN0002",
        title: "[Shader] class must not be nested",
        messageFormat: "'{0}' is marked [Shader(...)] but is a nested class - Path generation only supports top-level classes",
        category: "Rin.Shade",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var shaderClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => GetShaderInfo(ctx))
            .Where(static info => info is not null);

        context.RegisterSourceOutput(shaderClasses, static (spc, info) => Execute(spc, info!.Value));
    }

    private static (INamedTypeSymbol Symbol, string Path)? GetShaderInfo(GeneratorSyntaxContext context)
    {
        var declaration = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(declaration);
        if (symbol is null) return null;

        var attribute = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == ShaderAttributeFullName);
        if (attribute is null) return null;

        return attribute.ConstructorArguments.FirstOrDefault().Value is string path ? (symbol, path) : null;
    }

    // A derived shader's Path hides the generated Path of a partial [Shader] base, so it needs `new`.
    private static bool HasShaderBase(INamedTypeSymbol symbol)
    {
        for (var current = symbol.BaseType; current is not null; current = current.BaseType)
            if (current.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == ShaderAttributeFullName) &&
                current.ContainingType is null &&
                current.DeclaringSyntaxReferences.Select(r => r.GetSyntax()).OfType<ClassDeclarationSyntax>()
                    .Any(d => d.Modifiers.Any(SyntaxKind.PartialKeyword)))
                return true;

        return false;
    }

    private static void Execute(SourceProductionContext context, (INamedTypeSymbol Symbol, string Path) info)
    {
        var (symbol, path) = info;

        if (symbol.ContainingType is not null)
        {
            context.ReportDiagnostic(Diagnostic.Create(NestedShaderClass,
                symbol.Locations.FirstOrDefault() ?? Location.None, symbol.Name));
            return;
        }

        var isPartial = symbol.DeclaringSyntaxReferences
            .Select(r => r.GetSyntax())
            .OfType<ClassDeclarationSyntax>()
            .Any(d => d.Modifiers.Any(SyntaxKind.PartialKeyword));

        if (!isPartial)
        {
            context.ReportDiagnostic(Diagnostic.Create(MissingPartial,
                symbol.Locations.FirstOrDefault() ?? Location.None, symbol.Name));
            return;
        }

        var literal = SymbolDisplay.FormatLiteral(path, quote: true);
        var hidesBasePath = HasShaderBase(symbol);

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        if (!symbol.ContainingNamespace.IsGlobalNamespace)
            builder.AppendLine($"namespace {symbol.ContainingNamespace.ToDisplayString()};");
        builder.AppendLine();
        builder.AppendLine($"partial class {symbol.Name}");
        builder.AppendLine("{");
        builder.AppendLine($"    public {(hidesBasePath ? "new " : "")}const string Path = {literal};");
        builder.AppendLine("}");

        context.AddSource($"{symbol.Name}.ShaderPath.g.cs", builder.ToString());
    }
}
