<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="$(EngineDir)Rin.World\Rin.World.csproj" />
        <ProjectReference Include="$(EngineDir)Rin.Core\Rin.Core.csproj" />
        <ProjectReference Include="..\Common\Examples.Common.csproj"/>
        <ProjectReference Include="$(ExperimentsDir)experiments.Docking\experiments.Docking.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="SharpGLTF.Core"/>
    </ItemGroup>

    <ItemGroup>
        <assets Include=".\assets\**"/>
        <Content Include="@(assets)">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
    <PropertyGroup>
        <DefaultItemExcludes>$(DefaultItemExcludes);assets\**\*.*</DefaultItemExcludes>
    </PropertyGroup>

</Project>
