<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Authors>TareHimself</Authors>
        <PackageId>TareHimself.Rin.Graphics.Vulkan</PackageId>
        <Title>Rin.Graphics.Vulkan</Title>
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

    <PropertyGroup>
        <PlatformRID Condition="'$(RuntimeIdentifier)' != ''">$(RuntimeIdentifier)</PlatformRID>
        <PlatformRID Condition="'$(RuntimeIdentifier)' == ''">$(NETCoreSdkRuntimeIdentifier)</PlatformRID>
        <DefineConstants Condition="$([MSBuild]::IsOSPlatform('Windows'))">OS_WINDOWS</DefineConstants>
        <DefineConstants Condition="$([MSBuild]::IsOSPlatform('Linux'))">OS_LINUX</DefineConstants>
        <DefineConstants Condition="$([MSBuild]::IsOSPlatform('OSX'))">OS_MAC</DefineConstants>
        <DefaultItemExcludes>$(DefaultItemExcludes);native\**\*.*;assets\**\*.*</DefaultItemExcludes>
    </PropertyGroup>

    <!--    Local refs i.e. project refs-->
    <ItemGroup Condition="'$(DepMode)' == 'local_file'">
        <ProjectReference Include="$(EngineDir)Rin.Core\Rin.Core.csproj" />
        <ProjectReference Include="$(SlangDir)Rin.Slang\Rin.Slang.csproj" />
    </ItemGroup>
    <!--    References from online feeds-->
    <ItemGroup Condition="'$(DepMode)' == 'online'">
        <PackageReference Include="TareHimself.Rin.Core"/>
        <PackageReference Include="TareHimself.Rin.Slang"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" PrivateAssets="All" />
        <PackageReference Include="TareHimself.Rin.Graphics.Vulkan.Native"/>
        <PackageReference Include="TerraFX.Interop.Vulkan"/>
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Meshes\" />
    </ItemGroup>
</Project>
