<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="$(EngineDir)Rin.Core\Rin.Core.csproj" />
        <PackageReference Include="JetBrains.Annotations" PrivateAssets="All" />
    </ItemGroup>

    <ItemGroup Label="Content">
        <EmbeddedResource Include="Content\**\*.*"/>
    </ItemGroup>

    <ItemGroup Label="Rin.Shade">
        <ProjectReference Include="$(ShadeDir)Rin.Shade\Rin.Shade.csproj" />
        <ProjectReference Include="$(ShadeDir)Rin.Shade.SourceGenerator\Rin.Shade.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>
    <PropertyGroup Label="Rin.Shade">
        <RinShadeDiscoverPrefix>Shaders/Rin/World/</RinShadeDiscoverPrefix>
        <RinShadeOutputSubpath>Content\Shaders\Rin\World\</RinShadeOutputSubpath>
    </PropertyGroup>
    <Import Project="$(RinMSBuildDir)RinShade.targets" />

    <ItemGroup>
      <ProjectReference Include="$(EngineDir)Rin.SourceGenerators\Rin.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BepuPhysics"/>
    </ItemGroup>

</Project>
