<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup Label="Content">
        <EmbeddedResource Include="Content\**\*.*" Exclude="Content\**\*.slang"/>
    </ItemGroup>

    <ItemGroup Label="Rin.Shade">
        <ProjectReference Include="$(ShadeDir)Rin.Shade\Rin.Shade.csproj" />
        <ProjectReference Include="$(ShadeDir)Rin.Shade.SourceGenerator\Rin.Shade.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>
    <PropertyGroup Label="Rin.Shade">
        <RinShadeDiscoverPrefix>Shaders/Slug/</RinShadeDiscoverPrefix>
        <RinShadeOutputSubpath>Content\Shaders\Slug\</RinShadeOutputSubpath>
    </PropertyGroup>
    <Import Project="$(RinMSBuildDir)RinShade.targets" />

    <ItemGroup>
        <ProjectReference Include="$(ExamplesDir)Common\Examples.Common.csproj"/>
        <ProjectReference Include="$(EngineDir)Rin.Core\Rin.Core.csproj" />
        <ProjectReference Include="$(EngineDir)Rin.Graphics.Vulkan\Rin.Graphics.Vulkan.csproj" />
        <ProjectReference Include="$(EngineDir)Rin.Audio.Miniaudio\Rin.Audio.Miniaudio.csproj" />
        <ProjectReference Include="$(EngineDir)Rin.SourceGenerators\Rin.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="SixLabors.Fonts"/>
        <PackageReference Include="JetBrains.Annotations" PrivateAssets="All" />
    </ItemGroup>

</Project>
