<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup Label="Content">
        <EmbeddedResource Include="Content\**\*.*" Exclude="Content\**\*.slang"/>
    </ItemGroup>

    <ItemGroup Label="Slang shaders">
        <RinSlangSource Include="Content\Slug\**\*.slang" />
    </ItemGroup>
    <PropertyGroup Label="Slang shaders">
        <RinSlangOutputSubpath>Content\Slug\</RinSlangOutputSubpath>
    </PropertyGroup>
    <Import Project="$(RinMSBuildDir)RinSlang.targets" />

    <ItemGroup>
        <ProjectReference Include="$(ExamplesDir)Common\Examples.Common.csproj"/>
        <ProjectReference Include="$(EngineDir)Rin.Core\Rin.Core.csproj" />
        <ProjectReference Include="$(EngineDir)Rin.Graphics.Vulkan\Rin.Graphics.Vulkan.csproj" />
        <ProjectReference Include="$(EngineDir)Rin.Audio.Miniaudio\Rin.Audio.Miniaudio.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="SixLabors.Fonts"/>
    </ItemGroup>

</Project>
