<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Common\Examples.Common.csproj"/>
        <ProjectReference Include="$(EngineDir)Rin.Graphics.Vulkan\Rin.Graphics.Vulkan.csproj" />
        <ProjectReference Include="$(EngineDir)Rin.Core\Rin.Core.csproj" />
    </ItemGroup>

</Project>
