set(RIN_BINARY_DIR ./build)
set(OUTPUT_DIR ${RIN_BINARY_DIR}/${RIN_BUILD_TYPE}/bin)
set(DOWNLOAD_DIR ${RIN_BINARY_DIR}/${RIN_BUILD_TYPE}/_dl)
set(CHECKPOINT_FILE ${RIN_BINARY_DIR}/${RIN_BUILD_TYPE}/_bass_checkpoint)

if(NOT EXISTS ${CHECKPOINT_FILE})
    if(NOT EXISTS ${OUTPUT_DIR})
        file(MAKE_DIRECTORY ${OUTPUT_DIR})
    endif()
    set(DOWNLOADED_FILE ${DOWNLOAD_DIR}/bass.zip)
    set(EXTRACTED_FOLDER ${DOWNLOAD_DIR}/bass)
    if(WIN32)
        set(OUTPUT_FILE ${OUTPUT_DIR}/bass.dll)
        if(NOT EXISTS OUTPUT_FILE)
            file(DOWNLOAD https://www.un4seen.com/files/bass24.zip ${DOWNLOADED_FILE} SHOW_PROGRESS)
            file(ARCHIVE_EXTRACT INPUT ${DOWNLOADED_FILE} DESTINATION ${EXTRACTED_FOLDER})
            file(COPY ${EXTRACTED_FOLDER}/x64/bass.dll DESTINATION ${OUTPUT_DIR})
        endif()
    elseif(LINUX)
        set(OUTPUT_FILE ${OUTPUT_DIR}/libbass.so)
        if(NOT EXISTS OUTPUT_FILE)
            file(DOWNLOAD https://www.un4seen.com/files/bass24-linux.zip ${DOWNLOADED_FILE} SHOW_PROGRESS)
            file(ARCHIVE_EXTRACT INPUT ${DOWNLOADED_FILE} DESTINATION ${EXTRACTED_FOLDER})
            file(COPY ${EXTRACTED_FOLDER}/libs/x86_64/libbass.so DESTINATION ${OUTPUT_DIR})
        endif()
    elseif(APPLE)
        set(OUTPUT_FILE ${OUTPUT_DIR}/libbass.dylib)
        if(NOT EXISTS OUTPUT_FILE)
            file(DOWNLOAD https://www.un4seen.com/files/bass24-osx.zip ${DOWNLOADED_FILE} SHOW_PROGRESS)
            file(ARCHIVE_EXTRACT INPUT ${DOWNLOADED_FILE} DESTINATION ${EXTRACTED_FOLDER})
            file(COPY ${EXTRACTED_FOLDER}/libbass.dylib DESTINATION ${OUTPUT_DIR})
        endif()
    endif()
    file(REMOVE_RECURSE ${DOWNLOAD_DIR})
    file(TOUCH ${CHECKPOINT_FILE}) 
endif()