<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsAotCompatible>true</IsAotCompatible>
        <PackageId>TareHimself.Rin.Graphics.Null</PackageId>
        <Title>Rin.Graphics.Null</Title>
        <Authors>TareHimself</Authors>
        <Version>1.0.0</Version>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="$(EngineDir)Rin.Core\Rin.Core.csproj" />
    </ItemGroup>

</Project>
