<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <PackageId>TareHimself.Rin.Audio.Miniaudio</PackageId>
        <Authors>TareHimself</Authors>
        <Title>Rin.Audio.Miniaudio</Title>
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

    <PropertyGroup>
        <PlatformRID Condition="'$(RuntimeIdentifier)' != ''">$(RuntimeIdentifier)</PlatformRID>
        <PlatformRID Condition="'$(RuntimeIdentifier)' == ''">$(NETCoreSdkRuntimeIdentifier)</PlatformRID>
        <DefineConstants Condition="$([MSBuild]::IsOSPlatform('Windows'))">OS_WINDOWS</DefineConstants>
        <DefineConstants Condition="$([MSBuild]::IsOSPlatform('Linux'))">OS_LINUX</DefineConstants>
        <DefineConstants Condition="$([MSBuild]::IsOSPlatform('OSX'))">OS_MAC</DefineConstants>
        <DefaultItemExcludes>$(DefaultItemExcludes);native\**\*.*</DefaultItemExcludes>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" PrivateAssets="All"/>
        <PackageReference Include="TareHimself.Rin.Audio.Miniaudio.Native" />
    </ItemGroup>

    <ItemGroup Condition="'$(DepMode)' == 'local_file'">
        <ProjectReference Include="$(EngineDir)Rin.Core\Rin.Core.csproj" />
    </ItemGroup>

    <ItemGroup Condition="'$(DepMode)' == 'online'">
        <PackageReference Include="TareHimself.Rin.Core"/>
    </ItemGroup>
</Project>
