#!/usr/bin/env python3
"""Generate Shade/Rin.Shade/Shader.Math.cs: [SlangExpression]-bound static extern methods for
Slang's common math builtins, one explicit overload per relevant width (float, Vector2/3/4) -
Rin.Shade doesn't support generic methods (SHADE0008), so each width needs its own overload
rather than a single generic declaration.

Run from anywhere; writes directly to Shade/Rin.Shade/Shader.Math.cs relative to the repo root.
"""

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "Shade" / "Rin.Shade" / "Shader.Math.cs"

ALL_WIDTHS = [1, 2, 3, 4]  # 1 = float
VECTOR_WIDTHS = [2, 3, 4]


def type_name(width):
    return "float" if width == 1 else f"Vector{width}"


def slang_name(name):
    # Slang's own builtins are all-lowercase (smoothstep, not smoothStep) - unlike Rin.Shade's own
    # camelCase field/method convention, which only lowercases the leading letter.
    return name.lower()


def declare(name, widths, params, return_of):
    """params: list of (csharp_param_name, width_or_None_for_float_scalar) where None means
    always float regardless of the overload's own width. return_of: 'self' (same as overload
    width) or 'float' (always scalar)."""
    lines = []
    for width in widths:
        t = type_name(width)
        arg_list = ", ".join(
            f"{'float' if w is None else t} {pname}" for pname, w in params
        )
        template_args = ", ".join(f"@{i}" for i in range(len(params)))
        return_type = "float" if return_of == "float" else t
        lines.append(f'    [SlangExpression("{slang_name(name)}({template_args})")]')
        lines.append(f"    public static extern {return_type} {name}({arg_list});")
    return lines


def main():
    lines = []

    # T f(x) - per-component, valid on a bare float too.
    for name in ["Abs", "Sign", "Floor", "Ceil", "Round", "Frac", "Sqrt", "Rsqrt",
                 "Saturate", "Exp", "Exp2", "Log", "Log2", "Sin", "Cos", "Tan", "Asin", "Acos", "Atan",
                 "Radians", "Degrees"]:
        lines += declare(name, ALL_WIDTHS, [("x", "self")], "self")
        lines.append("")

    # T f(a, b) - per-component, valid on a bare float too.
    for name in ["Min", "Max", "Pow", "Step", "Atan2"]:
        lines += declare(name, ALL_WIDTHS, [("a", "self"), ("b", "self")], "self")
        lines.append("")

    # T f(a, b, c) - per-component, valid on a bare float too.
    lines += declare("Clamp", ALL_WIDTHS, [("x", "self"), ("lo", "self"), ("hi", "self")], "self")
    lines.append("")
    lines += declare("SmoothStep", ALL_WIDTHS, [("edge0", "self"), ("edge1", "self"), ("x", "self")], "self")
    lines.append("")

    # T f(a, b, t) - t is always a scalar blend factor, even for vector a/b.
    lines += declare("Lerp", ALL_WIDTHS, [("a", "self"), ("b", "self"), ("t", None)], "self")
    lines.append("")

    # Vector-only: whole-vector ops, not meaningful on a bare float.
    lines += declare("Normalize", VECTOR_WIDTHS, [("v", "self")], "self")
    lines.append("")
    lines += declare("Length", VECTOR_WIDTHS, [("v", "self")], "float")
    lines.append("")
    lines += declare("Dot", VECTOR_WIDTHS, [("a", "self"), ("b", "self")], "float")
    lines.append("")
    lines += declare("Distance", VECTOR_WIDTHS, [("a", "self"), ("b", "self")], "float")
    lines.append("")
    lines += declare("Reflect", VECTOR_WIDTHS, [("i", "self"), ("n", "self")], "self")
    lines.append("")
    lines += declare("Refract", VECTOR_WIDTHS, [("i", "self"), ("n", "self"), ("eta", None)], "self")
    lines.append("")

    # Cross is only defined for 3-vectors.
    lines += declare("Cross", [3], [("a", "self"), ("b", "self")], "self")

    body = "\n".join(("    " + l) if l else l for l in lines).rstrip("\n") + "\n"

    header = '''using System.Numerics;

namespace Rin.Shade;

// [SlangExpression]-bound math builtins, one overload per width (generics aren't supported, SHADE0008).
// Generated by scripts/gen_math_intrinsics.py - do not hand-edit, regenerate instead.
public abstract partial class Shader
{
    public static class Math
    {
'''
    footer = "    }\n}\n"

    content = header + body + footer

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content, newline="\n")

    total = content.count("public static extern")
    print(f"wrote {OUTPUT_PATH} with {total} intrinsic overloads")


if __name__ == "__main__":
    main()
