#!/usr/bin/env python3
"""Generate Shade/Rin.Shade/Swizzles.cs: every 1-4 letter swizzle combination (repeats and
reorderings included, e.g. .Xxxx, .Zyx - not just distinct-component reorderings) over both the
xyzw and rgba naming schemes, for Vector2/Vector3/Vector4 as C# 14 extension properties.

Run from anywhere; writes directly to Shade/Rin.Shade/Swizzles.cs relative to the repo root.
"""

import itertools
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "Shade" / "Rin.Shade" / "Swizzles.cs"

FIELD = {"x": "X", "y": "Y", "z": "Z", "w": "W",
         "r": "X", "g": "Y", "b": "Z", "a": "W"}

WIDTHS = [2, 3, 4]  # Vector2 / Vector3 / Vector4 as source receivers


def result_type(n):
    return "float" if n == 1 else f"Vector{n}"


def body(letters):
    if len(letters) == 1:
        return f"v.{FIELD[letters]}"
    args = ", ".join(f"v.{FIELD[c]}" for c in letters)
    return f"new({args})"


def prop_name(letters):
    # Lowercase, not PascalCase: makes the C# call site read identically to the Slang it mirrors
    # (color.rgb in both languages, not color.Rgb) - see the InconsistentNaming suppression below.
    return letters


def gen_block(width):
    xyzw = "xyzw"[:width]
    rgba = "rgba"[:width]
    lines = [f"    extension(Vector{width} v)", "    {"]

    # xyzw scheme: skip length 1 - already covered by the real X/Y/Z/W fields, and real instance
    # members win over extension members in lookup, so a generated alias would be unreachable dead code.
    for length in range(2, 5):
        for combo in itertools.product(xyzw, repeat=length):
            letters = "".join(combo)
            lines.append(f"        public {result_type(length)} {prop_name(letters)} => {body(letters)};")

    # rgba scheme: include length 1 - no real R/G/B/A fields exist, so these are genuinely reachable.
    for length in range(1, 5):
        for combo in itertools.product(rgba, repeat=length):
            letters = "".join(combo)
            lines.append(f"        public {result_type(length)} {prop_name(letters)} => {body(letters)};")

    lines.append("    }")
    return "\n".join(lines)


def main():
    header = '''using System.Diagnostics.CodeAnalysis;
using System.Numerics;

namespace Rin.Shade;

/// <summary>
/// Read swizzles as C# 14 extension properties, generated for every 1-4 letter combination
/// (repeats and reorderings included, e.g. .xxxx, .zyx) over both the xyzw and rgba naming
/// schemes - matches how real shader swizzles work, not just distinct-component reorderings.
/// Named lowercase on purpose, so the C# call site reads identically to the Slang it mirrors
/// (color.rgb in both languages, not color.Rgb) - hence the InconsistentNaming suppression below.
/// Verified against Roslyn 5.3.0: a call-site access (e.g. color.rgb) resolves as an ordinary
/// IPropertyReferenceOperation whose ContainingType has TypeKind.Extension - the transpiler
/// pattern-matches on that plus the property name instead of walking the property body, and
/// emits the literal swizzle text as-is.
/// Write swizzles are deliberately not supported - reconstruct instead
/// (`color = new Vector4(x, color.Y, color.Z, color.W)`).
/// Generated by scripts/gen_swizzles.py - do not hand-edit, regenerate instead.
/// </summary>
[SuppressMessage("ReSharper", "InconsistentNaming")]
public static class Swizzles
{
'''
    footer = "}\n"

    blocks = [gen_block(width) for width in WIDTHS]
    content = header + "\n\n".join(blocks) + "\n" + footer

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content, newline="\n")

    total = content.count(" => ")
    print(f"wrote {OUTPUT_PATH} with {total} swizzle properties")


if __name__ == "__main__":
    main()
