<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>


    <ItemGroup>
        <ProjectReference Include="..\..\Rin.Audio.Miniaudio\Rin.Audio.Miniaudio.csproj" />
        <ProjectReference Include="..\..\Rin.Graphics.Vulkan\Rin.Graphics.Vulkan.csproj" />
        <ProjectReference Include="..\..\Rin.Core\Rin.Core.csproj" />
    </ItemGroup>

</Project>
