<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="$(EngineDir)Rin.Core\Rin.Core.csproj" />
        <ProjectReference Include="..\Common\Examples.Common.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="SpotifyExplode"/>
        <PackageReference Include="YoutubeExplode" />
    </ItemGroup>
    <PropertyGroup>
        <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
    </PropertyGroup>
</Project>
